
rexray:
    image: rancher/storage-rbd:v0.8.9
    stdin_open: true
    tty: true
    privileged: true
    net: host
    volumes:
    - /run:/run
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
        STACK_NAME: ${SCALEIO_STACK_NAME}
        SYSTEM_ID: ${SCALEIO_SYSTEM_ID}
        MDM_IP:    ${SCALEIO_MDM_IP}
    labels:
        io.rancher.container.pull_image: always
        io.rancher.container.dns: true
